# Evaluation / PoC values for JFrog Platform
# Bundled PostgreSQL, no Xray/Distribution/RabbitMQ
postgresql:
  enabled: true

xray:
  enabled: false
distribution:
  enabled: false
rabbitmq:
  enabled: false

# Required for fresh install via Argo CD
preUpgradeHook:
  enabled: false
upgradeHookSTSDelete:
  enabled: false

artifactory:
  nginx:
    tlsSecretName: jfrog-platform-tls   # use your pre-created secret
    service:
      type: NodePort